### ISSUE TITLE
How to use it with Apollo Server?

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [4Catalyzer/graphql-validation-complexity#21]
Is it possible to use it with [Apollo Server](https://github.com/apollographql/apollo-server)? More precisely with [apollo-server-express](https://www.npmjs.com/package/apollo-server-express)?

If yes, could you please add the sample code to `README.md`?

**Comment by taion** [comment]
It's just via `validationRules` in https://www.apollographql.com/docs/apollo-server/v2/api/apollo-server.html#Parameters. Do the docs for that really belong here though? It's a more general problem.
