### ISSUE TITLE
unbreak schema introspection query.

### ISSUE THREAD

**Issue by chirag04** [4Catalyzer/graphql-validation-complexity#4]
should we special case introspection queries?

**Comment by taion** [comment]
Does this break GraphiQL entirely? Or does GraphiQL only introspect small parts of the schema at once?

Regardless, limiting introspection into production servers is not a terrible thing.

**Comment by chirag04** [comment]
This break `GraphiQL` entirely. Problem is that this breaks introspection in dev mode. maybe this can be a flag that special cases introspection queries?

**Comment by jquense** [comment]
perhaps you just give fields with leading `__` a cost of 0 always? the prefix is reserved for internal fields anyway.

**Comment by jquense** [comment]
or make it configurable anyway

**Comment by taion** [comment]
Hmm: https://github.com/graphql/graphql-js/blob/master/src/utilities/introspectionQuery.js#L74-L105

I wonder if we can special-case specifically this query.

**Comment by chirag04** [comment]
^yes. sent a PR.
